services:
  explo:
    image: ghcr.io/lumepart/explo:latest
    restart: unless-stopped
    container_name: explo
    volumes:
      - /path/to/.env:/opt/explo/.env
      - /path/to/musiclibrary/explo:$DOWNLOAD_DIR # has to be in the same path you have your music system pointed to (it's recommended to put explo under a subfolder)
      # - $PLAYLIST_DIR:$PLAYLIST_DIR # for MPD.
    environment:
      - CRON_SCHEDULE=15 00 * * 2 # Runs weekly, every Tuesday 15 minutes past midnight (UTC time)